import 'jquery';
import "./backbone/config/config";
import "./backbone/models/models";
import "./backbone/views/AddImage"
import "./backbone/views/Worker";
import "./backbone/views/ImageDetails";
import "./backbone/init/init";
import "./main-script";
import "./script";
import "./worker";
